version: "3.1"

services:
  db:
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: task_management
      MYSQL_ROOT_PASSWORD: password

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
    volumes:
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
