services:
  db:
    container_name: db
    image: mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: task_management
      MYSQL_ROOT_PASSWORD: password

  server:
    build: .
    env_file:
      - .env
    ports:
      - 8080:8080
    depends_on:
      - db

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - DEBUG=1
    volumes:
      - "./localstack-data:/var/lib/localstack"
      - "/var/run/docker.sock:/var/run/docker.sock"
