name: Deploy Golang application

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
      - name: Create .env file
        run: echo "PORT=${{ secrets.PORT }}" >> .env
      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build Docker image
        run: docker build -t rodrigorvsn/pam .
      - name: Push iamge to Docker Hub
        run: docker push rodrigorvsn/pam:latest
  deploy:
    needs: build
    runs-on: self-hosted
    steps:
      - name: Pull Docker image
        run: docker pull rodrigorvsn/pam:latest
      - name: Delete old container
        run: docker rm -f pam
      - name: Run Docker container
        run: docker run -d -p 8080:8080 --name pam rodrigorvsn/pam
